spring.application.name=hisabPotro
server.port=8000
spring.profiles.active=mysql

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=orchidpust@gmail.com
spring.mail.password=izbtyevsczjcbgqv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Your local Excel file path
local.excel.file.path=C:\\data\\shopping_data.xlsx

##C:\data/shopping_data.xlsx  the shopping data location is always here